#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE ROLE seatguard_app WITH LOGIN PASSWORD '${DB_APP_PASSWORD:-seatguard_app}';
GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO seatguard_app;
GRANT USAGE ON SCHEMA public TO seatguard_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO seatguard_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO seatguard_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO seatguard_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO seatguard_app;
EOSQL
